"""Total pages column added in documents table

Revision ID: 1068d2ec8c09
Revises: 
Create Date: 2026-06-14 19:02:18.184419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1068d2ec8c09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('total_pages', sa.Integer(), nullable=True))
    op.alter_column('documents', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('documents', 'total_pages')
    # ### end Alembic commands ###
